#!/usr/bin/env python3
"""Print the supported CUDA surface from the sources of truth (README.md, "Supported CUDA surface", carries the summary):

  host API      exported cuda*/cu* symbols of toolkit/lib64/libcudart.dylib (nm)
  device        the lowering tables in cpp/mvcc-llvm/msl_emitter.cpp: NVVM/LLVM intrinsics, libdevice (__nv_*)
                functions, inline-PTX mnemonics and the mma.sync variants
  headers       the clean-room headers under include/

Usage: tools/gen_surface.py            write the Markdown to stdout
       tools/gen_surface.py -o FILE    write it to FILE
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EMITTER = os.path.join(ROOT, "cpp/mvcc-llvm/msl_emitter.cpp")
DYLIB = os.path.join(ROOT, "toolkit/lib64/libcudart.dylib")


def function_body(src, name):
    """Text of `void Emitter::<name>(` up to the next `void Emitter::` at column 0."""
    m = re.search(r"^void Emitter::%s\(" % re.escape(name), src, re.M)
    if not m:
        sys.exit("gen_surface: %s not found in %s" % (name, EMITTER))
    n = re.search(r"^void Emitter::\w+\(", src[m.end():], re.M)
    return src[m.start(): m.end() + (n.start() if n else len(src))]


def host_api():
    out = subprocess.check_output(["nm", "-gU", DYLIB], text=True)
    syms = sorted({l.split()[-1].lstrip("_") for l in out.splitlines() if l.strip()})
    runtime = [s for s in syms if re.match(r"cuda[A-Z]", s)]
    driver = [s for s in syms if re.match(r"cu[A-Z]", s)]
    internal = [s for s in syms if s.startswith("__cuda")]
    return runtime, driver, internal


def device_tables():
    src = open(EMITTER).read()
    intr = function_body(src, "emitIntrinsic")
    nvvm = sorted(set(re.findall(r'"(llvm\.nvvm\.[\w.]+)"', intr)))
    generic = sorted(set(re.findall(r'"(llvm\.(?!nvvm)[\w.]+)"', intr)))
    lib = function_body(src, "emitLibdevice")
    # every `if (... n == "x" ...) fail(...)` names a function that is recognized and rejected with its own message
    # (fp64 names, "no Metal equivalent"); everything else compared against `n` is lowered
    rejected = set()
    for cond in re.findall(r'if \(([^{}\n]*)\)\s*\n?\s*fail\(', lib):
        rejected |= set(re.findall(r'n == "(\w+)"', cond))
    libdevice = set(re.findall(r'\b(?:UN|UNM|BIN|BINM)\("(\w+)"', lib))
    libdevice |= set(re.findall(r'n == "(\w+)"', lib))
    libdevice -= rejected
    asm = function_body(src, "emitInlineAsm")
    mnemonics = sorted(set(re.findall(r'\bm == "(\w+)"', asm)))
    mma = sorted(set(re.findall(r'"__mvcc_mma_(m\d+n\d+k\d+_\w+)"', asm)))
    return nvvm, generic, sorted(libdevice), sorted(rejected), mnemonics, mma


def headers():
    rows = []
    for dp, _, fs in sorted(os.walk(os.path.join(ROOT, "include"))):
        for f in sorted(fs):
            p = os.path.join(dp, f)
            rel = os.path.relpath(p, ROOT)
            txt = open(p, errors="replace").read()
            n = len(re.findall(r"__device__|__host__ __device__|__forceinline__", txt))
            rows.append((rel, txt.count("\n"), n))
    return rows


def mma_row(v):
    shape, dt, at, bt, ct = v.split("_")
    return "| `mma.sync.aligned.%s.row.col.%s.%s.%s.%s` |" % (shape, dt, at, bt, ct)


def render():
    runtime, driver, internal = host_api()
    nvvm, generic, libdevice, rejected, mnemonics, mma = device_tables()
    L = []
    w = L.append
    w("# Supported CUDA surface")
    w("")
    w("Generated by `tools/gen_surface.py` from the runtime's exported symbols and the compiler's lowering tables.")
    w("")
    w("What is *not* here is not supported: an unknown host API symbol fails to link, an unknown device intrinsic,")
    w("libdevice function or inline-PTX mnemonic is a compile error carrying the original name (`tools/gen_diagnostics.py`).")
    w("")
    w("## Host API (`libcudart.dylib`, also served as `libcuda.dylib`)")
    w("")
    w("%d runtime API entry points:" % len(runtime))
    w("")
    for s in runtime:
        w("- `%s`" % s)
    w("")
    w("%d driver API entry points:" % len(driver))
    w("")
    for s in driver:
        w("- `%s`" % s)
    w("")
    w("Registration hooks clang's host stub calls (`%s`)." % "`, `".join(internal))
    w("")
    w("## Device code")
    w("")
    w("### NVVM intrinsics (`%d` name prefixes)" % len(nvvm))
    w("")
    w("Matched by prefix, so every rounding/type suffix under a listed prefix is accepted (e.g. `llvm.nvvm.f2i.rn` covers")
    w("`.ftz` forms). Anything else under `llvm.nvvm.` is rejected.")
    w("")
    for s in nvvm:
        w("- `%s`" % s)
    w("")
    w("### Generic LLVM intrinsics (`%d`)" % len(generic))
    w("")
    for s in generic:
        w("- `%s`" % s)
    w("")
    w("### libdevice (`__nv_*`, %d functions)" % len(libdevice))
    w("")
    w("A `fast_` prefix (from `-use_fast_math`) selects Metal's `fast::` namespace; fp64 names (`__nv_sin`, `__nv_pow`, ...)")
    w("are a hard error because Apple GPUs have no fp64 (`README.md`, \"Differences from CUDA\").")
    w("")
    w(", ".join("`%s`" % s for s in libdevice))
    w("")
    if rejected:
        w("Recognized and rejected with a specific message: %s." % ", ".join("`%s`" % s for s in rejected))
        w("")
    w("### Inline PTX mnemonics (%d)" % len(mnemonics))
    w("")
    w("Inline `asm` is parsed with the PTX grammar (`cpp/mvcc-llvm/ptx_asm.cpp`) and lowered per instruction; predicated")
    w("(`@%p`) forms are supported. Mnemonics:")
    w("")
    w(", ".join("`%s`" % s for s in mnemonics))
    w("")
    w("`ld`/`st` cover `.global` with `.v2`/`.v4`/`.volatile`; `cp.async` covers `.cg`/`.ca.shared.global` with the")
    w("optional src-size (zero-fill) operand plus `commit_group`/`wait_group`/`wait_all`; `ldmatrix` covers `.x1/.x2/.x4`")
    w("and `.trans`; the `f16x2`/`bf16x2` forms of `add/sub/mul/fma/max/min`; `cvt.rn.f16x2.f32` and `cvt.rn.bf16x2.f32`.")
    w("")
    w("### `mma.sync` variants (%d)" % len(mma))
    w("")
    w("| variant |")
    w("|---|")
    for v in mma:
        w(mma_row(v))
    w("")
    w("`m16n8k16` f16/bf16 → f32 loops are additionally recovered onto Metal 4 TensorOps (`README.md`, \"Tensor cores\");")
    w("the others run through the exact fragment lowering.")
    w("")
    w("## Headers (`include/`)")
    w("")
    w("Clean-room, written from the public CUDA documentation. Counts are of `__device__`/`__host__ __device__` markers.")
    w("")
    w("| header | lines | device-marked declarations |")
    w("|---|---|---|")
    for rel, lines, n in headers():
        w("| `%s` | %d | %d |" % (rel, lines, n))
    w("")
    return "\n".join(L)


def main():
    text = render()
    if "-o" in sys.argv:
        out = sys.argv[sys.argv.index("-o") + 1]
        open(out, "w").write(text)
        print("wrote %s" % out)
        return
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
